name: Rust Build and Test

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - bugfix/*

  pull_request:
    branches:
      - main
      - develop

env:
  CARGO_TERM_COLOR: always

jobs:
  Build-Test-Format-Lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependancies
      run: sudo apt update && sudo apt install -y libudev-dev

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test --all-features

    - name: Check Format
      run: cargo fmt --check

    - uses: Swatinem/rust-cache@v1
